# Site settings
title: Lain's Blog - Volafile.io
email: lain@volafile.io
description: > # this means to ignore newlines until "baseurl:"
    Lain's Blog - Creator of Volafile.io, Node.js Hacker, Student from Germany
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.volafile.io" # the base hostname & protocol for your site
twitter_username: volafile
github_username:  laino

# Build settings
markdown: kramdown
