# Site settings
title: Nils Kuhnhenn
email: nils@volafile.io
description: > # this means to ignore newlines until "baseurl:"
    Nils Kuhnhenn - Creator of Volafile.io, Programmer, Student from Germany
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nilskuhnhenn.com" # the base hostname & protocol for your site
twitter_username: volafile
github_username:  laino

# Build settings
markdown: kramdown

permalink: /:short_year/:i_month/:title/
